import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated by scripts/build_sidebar.py
 * Docusaurus reads sidebar_position from each MDX front matter
 * and _category_.json files to build the ordered tree.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
