"""
Stage 3 — Sidebar Builder Agent
────────────────────────────────
Takes the list of written chapters and:
  1. Creates _category_.json in every category sub-directory (EN + ZH).
  2. Rewrites sidebars.ts to an autogenerated config so Docusaurus handles
     ordering via the front-matter sidebar_position values.

No LLM call needed — this is pure file manipulation.
"""
import json
import sys
from pathlib import Path

from config import (
    DOCS_EN_DIR, DOCS_ZH_DIR, SIDEBARS_FILE,
)

# ─────────────────────────────────────────────────────────────────────────────
# _category_.json helpers
# ─────────────────────────────────────────────────────────────────────────────

# Maps an English category slug to its Chinese display label.
# Extend this dict as your curriculum grows.
_ZH_CATEGORY_LABELS: dict[str, str] = {
    "foundations":             "基础篇",
    "prompt-engineering":     "提示词工程",
    "ai-assisted-development": "AI 辅助开发",
    "ai-agents":              "AI Agent",
    "real-projects":          "实战项目",
    "advanced-topics":        "进阶专题",
    "agent-mode":         "智能体模式",
    "advanced":           "进阶内容",
    "best-practices":     "最佳实践",
}


def _en_label(category_slug: str) -> str:
    """Turn a kebab-case slug into a Title Case English label."""
    return category_slug.replace("-", " ").title()


def _zh_label(category_slug: str) -> str:
    return _ZH_CATEGORY_LABELS.get(category_slug, _en_label(category_slug))


def _write_category_json(directory: Path, label: str, position: int) -> None:
    """Write a Docusaurus _category_.json file."""
    directory.mkdir(parents=True, exist_ok=True)
    payload = {"label": label, "position": position,
               "link": {"type": "generated-index"}}
    (directory / "_category_.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


# ─────────────────────────────────────────────────────────────────────────────
# sidebars.ts
# ─────────────────────────────────────────────────────────────────────────────

_SIDEBARS_TS = """\
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated by scripts/build_sidebar.py
 * Docusaurus reads sidebar_position from each MDX front matter
 * and _category_.json files to build the ordered tree.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
"""


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar Builder Agent
# ─────────────────────────────────────────────────────────────────────────────

def run_sidebar_agent(chapter_results: list[dict]) -> None:
    """
    chapter_results: list of dicts returned by run_writer_agent(), each with keys:
      chapter_id, slug, category, sidebar_position, title, en_path, zh_path
    """
    # ── 1. Collect unique categories, preserving existing positions ──────────
    # Read positions already written to disk so a partial run (--chapters)
    # doesn't reset previously assigned positions back to 1.
    category_positions: dict[str, int] = {}
    for cat_dir in sorted(DOCS_EN_DIR.iterdir()):
        cat_json = cat_dir / "_category_.json"
        if cat_json.exists():
            try:
                data = json.loads(cat_json.read_text())
                pos = data.get("position")
                if isinstance(pos, int):
                    category_positions[cat_dir.name] = pos
            except Exception:
                pass

    # Assign new positions to any categories not yet on disk,
    # starting after the highest existing position.
    cat_counter = max(category_positions.values(), default=0) + 1
    for ch in chapter_results:
        cat = ch.get("category")
        if cat and cat not in category_positions:
            category_positions[cat] = cat_counter
            cat_counter += 1

    # ── 2. Write _category_.json files ───────────────────────────────────────
    for cat, pos in category_positions.items():
        en_dir = DOCS_EN_DIR / cat
        zh_dir = DOCS_ZH_DIR / cat
        _write_category_json(en_dir, _en_label(cat), pos)
        _write_category_json(zh_dir, _zh_label(cat), pos)
        print(f"[Sidebar Agent]    ✓  _category_.json → {cat}/ (EN + ZH)")

    # ── 3. Rewrite sidebars.ts ────────────────────────────────────────────────
    SIDEBARS_FILE.write_text(_SIDEBARS_TS, encoding="utf-8")
    print(f"[Sidebar Agent]    ✓  sidebars.ts → autogenerated")

    # ── 4. Summary ────────────────────────────────────────────────────────────
    print(f"[Sidebar Agent]    Indexed {len(chapter_results)} chapters, "
          f"{len(category_positions)} categories.")


# ─────────────────────────────────────────────────────────────────────────────
# Standalone entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    from config import SPECS_DIR

    if not SPECS_DIR.exists():
        sys.exit("No specs found — run generate_specs.py first.")

    # Reconstruct chapter_results from spec files + existence check
    results = []
    for spec_file in sorted(SPECS_DIR.glob("*.json")):
        spec = json.loads(spec_file.read_text())
        from config import DOCS_EN_DIR as EN, DOCS_ZH_DIR as ZH
        slug = spec["slug"]
        cat  = spec.get("category")
        en_p = (EN / cat / f"{slug}.mdx") if cat else (EN / f"{slug}.mdx")
        zh_p = (ZH / cat / f"{slug}.mdx") if cat else (ZH / f"{slug}.mdx")
        results.append({
            "chapter_id":      spec["chapter_id"],
            "slug":            slug,
            "category":        cat,
            "sidebar_position": spec["sidebar_position"],
            "title":           spec["title"],
            "en_path":         str(en_p),
            "zh_path":         str(zh_p),
        })

    run_sidebar_agent(results)
